#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/bin/mips-linux-uclibc-gcc -fPIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_NO_KRB5 -DOPENSSL_NO_HW -Os -fomit-frame-pointer -Wall -DB_ENDIAN -DOPENSSL_NO_IDEA  -DOPENSSL_NO_BF -DOPENSSL_NO_CAST -DOPENSSL_NO_MD2 -DOPENSSL_NO_MD4 -DOPENSSL_NO_RIPEMD -DOPENSSL_NO_MDC2 -DOPENSSL_NO_RC2 -Werror=return-type -Werror=uninitialized -Werror=frame-larger-than=1024 -DOPENSSL_NO_ENGINE  -Wl,-rpath, -L/home/wmeng/cl/c2000a/bcmcpe/targets/963268BGW/fs.install/lib -L/home/wmeng/cl/c2000a/bcmcpe/targets/963268BGW/fs.install/lib/public -Wno-error=uninitialized -I/opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include -Wl,-L/opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/lib -Wl,-L/opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/lib"
  #define PLATFORM "mips"
  #define DATE "Fri Oct  9 14:33:49 CST 2015"
#endif
