/* this file is automatically generated from top level Makefile */
#ifndef __BCM_SWVERSION_H__
#define __BCM_SWVERSION_H__
#define BCM_REL_VERSION CAC002-31
#define BCM_REL_RELEASE 30
#define BCM_REL_PATCH 74
#define BCM_SW_VERSIONCODE (CAC002-31*65536+30*256+74)
#define BCM_SW_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))
#define BCM_REL_VERSION2 CAH005-31
#define BCM_REL_RELEASE2 30
#define BCM_REL_PATCH2 74
#define BCM_SW_VERSIONCODE2 (CAH005-31*65536+30*256+74)
#define BCM_SW_VERSION2(a,b,c) (((a) << 16) + ((b) << 8) + (c))
#endif
