/* this file is automatically generated from top level Makefile */
#ifndef __BCM_SWVERSION_H__
#define __BCM_SWVERSION_H__
#define BCM_REL_VERSION 
#define BCM_REL_RELEASE 
#define BCM_REL_PATCH 
#define BCM_SW_VERSIONCODE (*65536+*256+)
#define BCM_SW_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))
#define BCM_REL_VERSION2 
#define BCM_REL_RELEASE2 
#define BCM_REL_PATCH2 
#define BCM_SW_VERSIONCODE2 (*65536+*256+)
#define BCM_SW_VERSION2(a,b,c) (((a) << 16) + ((b) << 8) + (c))
#endif
